name: search-engines-urls-push

on:
  push:
    branches:
      - main

jobs:
  search-engines-urls-push:
    runs-on: ubuntu-latest
    name: search-engines-urls-push
    steps:
      - name: search-engines-urls-push
        id: search-engines-urls-push
        uses: 3Alan/search-engines-urls-push@v0.2.1
        with:
          site: ${{ secrets.SITE }}
          sitemap: ${{ secrets.SITEMAP }}
          count: ${{ secrets.COUNT }}
          baidu-token: ${{ secrets.BAIDU_TOKEN }}
